name: Saludo usando variables llaves
run-name: ¡Estoy aprendiendo a usar Variables!
on:
  workflow_dispatch
env:
  DIA_DE_SEMANA: Lunes
jobs:
  saludo-variables:
    runs-on: ubuntu-latest
    env:
      SALUDO: Hola
    steps:
      - name: Saludar
        run: echo "$SALUDO, $NOMBRE1. Hoy es $DIA_DE_SEMANA!"
        env:
          NOMBRE1: Juan
  saludo-secretos:
    runs-on: ubuntu-latest
    env:
        SALUDO: Hola Prueba
    steps:
        - name: Saludar secretos
          run: echo "$SALUDO, ${{ varS.NOMBRE  }}. TU CONTRAEÑA ES ${{ secrets.CONTRASENA }}  !"
          
